  version: "3.8"

  services:
    localstack:
      image: localstack/localstack:latest
      container_name: localstack
      ports:
        - "4566:4566"
      environment:
        - SERVICES=s3,sqs
        - DEFAULT_REGION=eu-central-1
        - HOSTNAME_EXTERNAL=localstack
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
      volumes:
        - localstack-data:/var/lib/localstack
      networks:
        - app-network
      restart: unless-stopped

      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
        interval: 5s
        timeout: 3s
        retries: 10

    terraform:
      image: hashicorp/terraform:light
      container_name: terraform
      working_dir: /workspace
      volumes:
        - ./terraform:/workspace
      environment:
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
      entrypoint: >
        sh -c "
          terraform init &&
          terraform apply -auto-approve
        "
      depends_on:
        localstack:
          condition: service_healthy
      networks:
        - app-network

    frontend:
      build:
        context: ./frontend
      container_name: frontend
      ports:
        - "3000:3000"
      environment:
        - AWS_ENDPOINT=http://localstack:4566
        - AWS_REGION=eu-central-1
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
        - BUCKET_NAME=localstack-bucket
      networks:
        - app-network
      depends_on:
        - terraform
      restart: unless-stopped

    inspector:
      build:
        context: ./inspector
      container_name: inspector
      ports:
        - "8000:8000"
      environment:
        - AWS_ENDPOINT=http://localstack:4566
        - AWS_REGION=eu-central-1
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
      networks:
        - app-network
      depends_on:
        - terraform
      restart: unless-stopped

  volumes:
    localstack-data:

  networks:
    app-network:
